function return_val = gq_3p(integrand_func, x1, x2)
% Integrates a 1-dimension function by using the Gaussian quadrature method with 3 points selected.
% Fu Chunhao, 22 April 2020
%
% function return_val = gq_3p(integrand_func, x1, x2)
    factor_plus = 0.5 .* (x2 + x1);
    factor_minus = 0.5 .* (x2 - x1);
    return_val = factor_minus .* ( ...
                     5.0 / 9.0 .* ( ...
                         integrand_func(factor_plus - sqrt(15.0) / 5.0 .* factor_minus) + ...
                         integrand_func(factor_plus + sqrt(15.0) / 5.0 .* factor_minus) ...
                     ) + ...
                     8.0 / 9.0 .* (  ...
                         integrand_func(factor_plus) ...
                     ) ...
                 );
end
